services:
  api:
    build: .
    container_name: trading_analysis
    restart: always
    command: npm run dev
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 3000:3000

  db:
    image: mongo:8.0.1
    restart: always
    volumes:
      - mongo-data-cloudfide:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data-cloudfide:
